server:
  port: 8083

kfcrpc:
  zkRoot: kfcrpc
  zkServer: localhost:2181
  provider:
   metas:
     dc: bj
     gray: false
     unit: 8081
  app:
    id: p1
    env: dev
    namespace: public


logging:
  level:
    root: info
    com.cola.kfcrpc: debug