spring:
  application:
    name: app2
app:
  id: app2
apollo:
  cacheDir: /opt/data/
  cluster: default
  meta: http://localhost:8080
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    enabled: true
    namespaces: app2,application
    eagerLoad:
      enabled: false
server:
  port: 9051

kfcrpc:
  zkRoot: kfcrpc
  zkServer: localhost:2181
  provider:
   metas:
     dc: bj
     gray: false
     unit: 8081
  app:
    id: p1
    env: dev
    namespace: public


logging:
  level:
    root: info
    com.cola.kfcrpc: debug
    com.ctrip: debug